# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39be87df296269333c5bee56763d543b7c33b0ea62c96edee87b1f3565605808fd639e6c23c415dd5bde8c69c84ff3b93907cc94933646ae6079296dd8b47896

test:
  secret_key_base: 781d04617ee1c785488d3a6e54f9c02ee99814789a1de90db5a239da62523e07b886a6b9f0cfe7cc963ebbe85bd8f7e9f7198f5a6dc2574292be0dd913e46cc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
